### PR TITLE
feat buy & sell kin screen

### PR DESCRIPTION
**Pull request by cdhiraj40**
| Buy & Sell Screen | Account sheet |
| --- | --- |
| Screenshot_1701630293| Screenshot_1701630690  |

Remaining changes:
- [ ] Translations
- [ ] Analytics on video shared

### CODE REVIEW

**Comment by jeffyanta** [comment]
On my P8P, the video isn't utilizing all of the space.

Screenshot_20231203-184631

**Comment by cdhiraj40** [comment]
> I'm also noticing the ripple on the share button come in and out very quickly when pressed. It appears very "grainy".

I think that's the native Android thing, can you check if you are experiencing the same when trying to share bills?

**Comment by cdhiraj40** [comment]
@jeffyanta updated the PR!

**Comment by jeffyanta** [comment]
@cdhiraj40 just tried the latest changes. Looks like the sizing is correct. I am noticing the white highlight upon pressing the video extends beyond the video preview. Note the extra padding at the bottom, and curved edges.

**Comment by cdhiraj40** [comment]
> @cdhiraj40 just tried the latest changes. Looks like the sizing is correct. I am noticing the white highlight upon pressing the video extends beyond the video preview. Note the extra padding at the bottom, and curved edges.
> 
> 

ah my bad, the latest changes should fix it!

**Comment by jeffyanta** [comment]
On the share button issue, I've uploaded a video to show what's going on my device. You might need to zoom in on the top share button, since it's quite subtle.


https://github.com/code-payments/code-android-app/assets/5760385/d66c9909-35c7-4844-b506-aad261803264

**Review by jeffyanta — APPROVED** [review]

**Pull request merged**
